#!/usr/bin/env python3
"""Generate combinatorial test-lab scenarios from a declarative matrix.

Hand-writing hundreds of near-identical scenarios does not scale and rots fast,
so the deep combinatorial layer is generated instead. Every cell of the matrix
below pairs an input value with the behaviour the runtime is specified to
produce, so a generated assertion failing means a real defect — these are not
snapshots of current behaviour.

Generated files carry a `gen-` prefix and a "generated" header. They are safe to
delete and regenerate:

    test-lab/generate-matrix.py            # write pipelines + scenarios
    test-lab/generate-matrix.py --clean    # remove generated files only
    test-lab/generate-matrix.py --list     # print what would be generated

Expected values are JSON-encoded the way Go's encoding/json renders them, so the
scenarios can assert on a `"target":value` substring of the batched request body.
"""
from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

LAB = Path(__file__).resolve().parent
PIPELINES = LAB / "pipelines"
SCENARIOS = LAB / "scenarios"
PREFIX = "gen-"

SOURCE = "http://localhost:18080/source/matrix/record"
SINK = "http://localhost:18080/destination/matrix/sink"
SINK_PATH = "/destination/matrix/sink"

HEADER = "# GENERATED by test-lab/generate-matrix.py — do not edit by hand.\n"


@dataclass
class Case:
    """One matrix cell: a pipeline plus the assertions it must satisfy."""

    name: str
    description: str
    filters: list[dict]
    # Substrings expected in the request body reaching the sink.
    body_contains: list[str] = field(default_factory=list)
    # Substrings that must NOT appear anywhere in the sink body.
    body_absent: list[str] = field(default_factory=list)
    expect_status: str = "success"
    log_contains: list[str] = field(default_factory=list)
    axis: str = "misc"
    # Merged into the generated input/output blocks, for cells that need a
    # different source, pagination config, method, requestMode or success block.
    input_override: dict = field(default_factory=dict)
    output_override: dict = field(default_factory=dict)
    # Assertions that do not target the default sink body.
    extra_assertions: list[dict] = field(default_factory=list)
    # Set when the cell asserts nothing on the default sink path.
    skip_sink_assertions: bool = False


def go_json(value: object) -> str:
    """Render a value the way Go's encoding/json would, for substring matching."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float) and value.is_integer():
        # Go prints float64(1) as 1, not 1.0
        return str(int(value))
    return json.dumps(value, separators=(",", ":"), ensure_ascii=False)


def field_is(target: str, value: object) -> str:
    """The `"target":value` substring proving the field carries value."""
    return f'"{target}":{go_json(value)}'


# --------------------------------------------------------------------------
# Axis: mapping transforms — every op against the input kinds it must handle
# --------------------------------------------------------------------------


def transform_cases() -> list[Case]:
    """One case per (op, input kind), asserting the specified result.

    Semantics are taken from internal/modules/filter/mapping_transforms.go:
    string-only ops pass non-strings through untouched, the numeric/bool
    converters error on unparseable input, toObject errors on non-maps.
    """
    ok: list[tuple[str, dict, str, object]] = [
        # (label, transform, source field, expected output)
        ("trim-string", {"op": "trim"}, "padded", "spaced value"),
        ("trim-nonstring-passthrough", {"op": "trim"}, "int_val", 7),
        ("lowercase-string", {"op": "lowercase"}, "mixed", "mixed case"),
        ("lowercase-nonstring-passthrough", {"op": "lowercase"}, "bool_val", True),
        ("uppercase-string", {"op": "uppercase"}, "mixed", "MIXED CASE"),
        ("uppercase-nonstring-passthrough", {"op": "uppercase"}, "int_val", 7),
        ("tostring-from-int", {"op": "toString"}, "int_val", "7"),
        ("tostring-from-bool", {"op": "toString"}, "bool_val", "true"),
        ("tostring-from-string", {"op": "toString"}, "mixed", "MiXeD Case"),
        ("toint-from-string", {"op": "toInt"}, "int_str", 42),
        ("toint-from-whole-float", {"op": "toInt"}, "int_val", 7),
        ("toint-from-bool", {"op": "toInt"}, "bool_val", 1),
        ("tofloat-from-string", {"op": "toFloat"}, "float_str", 98.5),
        ("tofloat-from-number", {"op": "toFloat"}, "float_val", 1.5),
        ("tobool-from-string", {"op": "toBool"}, "bool_str", True),
        ("tobool-from-number", {"op": "toBool"}, "int_val", True),
        ("toarray-wraps-scalar", {"op": "toArray"}, "mixed", ["MiXeD Case"]),
        ("toarray-passes-array", {"op": "toArray"}, "pipe_list", ["one", "two", "three"]),
        ("toobject-passes-map", {"op": "toObject"}, "obj", {"zone": "eu-west"}),
        (
            "split-default-separator-trims",
            {"op": "split"},
            "csv",
            ["alpha", "beta", "gamma"],
        ),
        (
            "split-explicit-separator",
            {"op": "split", "separator": ","},
            "csv",
            ["alpha", "beta", "gamma"],
        ),
        ("split-nonstring-passthrough", {"op": "split"}, "int_val", 7),
        (
            "join-default-separator",
            {"op": "join"},
            "pipe_list",
            "one,two,three",
        ),
        (
            "join-explicit-separator",
            {"op": "join", "separator": "|"},
            "pipe_list",
            "one|two|three",
        ),
        ("join-nonarray-passthrough", {"op": "join"}, "mixed", "MiXeD Case"),
        (
            "replace-regex",
            {"op": "replace", "pattern": "[^0-9+]", "replacement": ""},
            "phone",
            "+331234567",
        ),
        (
            "replace-nonstring-passthrough",
            {"op": "replace", "pattern": "7", "replacement": "9"},
            "int_val",
            7,
        ),
        (
            "dateformat-iso-to-date",
            {"op": "dateFormat", "format": "YYYY-MM-DD"},
            "date_iso",
            "2026-03-04",
        ),
        (
            "dateformat-date-only-input",
            {"op": "dateFormat", "format": "DD/MM/YYYY"},
            "date_only",
            "04/03/2026",
        ),
        (
            "dateformat-time-tokens",
            {"op": "dateFormat", "format": "HH:mm:ss"},
            "date_iso",
            "05:06:07",
        ),
        (
            "dateformat-two-digit-year",
            {"op": "dateFormat", "format": "YY-MM-DD"},
            "date_iso",
            "26-03-04",
        ),
        (
            "dateformat-nonstring-passthrough",
            {"op": "dateFormat", "format": "YYYY"},
            "int_val",
            7,
        ),
    ]

    failing: list[tuple[str, dict, str, str]] = [
        # (label, transform, source field, expected error fragment)
        ("toint-from-bad-string", {"op": "toInt"}, "bad_int_str", "cannot parse int from string"),
        (
            "toint-from-fractional-float",
            {"op": "toInt"},
            "float_val",
            "cannot convert float with fractional part to int",
        ),
        ("tofloat-from-bad-string", {"op": "toFloat"}, "bad_int_str", "cannot parse float from string"),
        ("tobool-from-bad-string", {"op": "toBool"}, "bad_bool_str", "cannot parse bool from string"),
        ("toobject-from-string", {"op": "toObject"}, "mixed", "cannot convert string to object"),
        ("dateformat-unparseable", {"op": "dateFormat", "format": "YYYY"}, "bad_date", "could not parse date"),
    ]

    cases: list[Case] = []
    for label, transform, src, expected in ok:
        cases.append(
            Case(
                name=f"transform-{label}",
                description=f"mapping transform {transform['op']} on {src} yields {expected!r}.",
                filters=[
                    {
                        "type": "mapping",
                        "mappings": [
                            {"source": "id", "target": "id"},
                            {"source": src, "target": "out", "transforms": [transform]},
                        ],
                    }
                ],
                body_contains=[field_is("out", expected)],
                axis="transform",
            )
        )
    for label, transform, src, err in failing:
        cases.append(
            Case(
                name=f"transform-{label}",
                description=(
                    f"mapping transform {transform['op']} on {src} cannot convert and "
                    "fails the pipeline under the default onError=fail."
                ),
                filters=[
                    {
                        "type": "mapping",
                        "mappings": [
                            {"source": src, "target": "out", "transforms": [transform]},
                        ],
                    }
                ],
                expect_status="error",
                log_contains=[err],
                axis="transform",
            )
        )
    return cases


# --------------------------------------------------------------------------
# Axis: onMissing strategies
# --------------------------------------------------------------------------


def on_missing_cases() -> list[Case]:
    cases = [
        Case(
            name="onmissing-setnull",
            description="onMissing=setNull writes an explicit null for an absent source.",
            filters=[
                {
                    "type": "mapping",
                    "mappings": [
                        {"source": "id", "target": "id"},
                        {"source": "no_such_field", "target": "out", "onMissing": "setNull"},
                    ],
                }
            ],
            body_contains=[field_is("out", None)],
            axis="onMissing",
        ),
        Case(
            name="onmissing-skipfield",
            description="onMissing=skipField leaves the target absent entirely.",
            filters=[
                {
                    "type": "mapping",
                    "mappings": [
                        {"source": "id", "target": "id"},
                        {"source": "no_such_field", "target": "skipped_out", "onMissing": "skipField"},
                    ],
                }
            ],
            body_contains=[field_is("id", "MTX-1")],
            body_absent=["skipped_out"],
            axis="onMissing",
        ),
        Case(
            name="onmissing-usedefault",
            description="onMissing=useDefault substitutes defaultValue for an absent source.",
            filters=[
                {
                    "type": "mapping",
                    "mappings": [
                        {"source": "id", "target": "id"},
                        {
                            "source": "no_such_field",
                            "target": "out",
                            "onMissing": "useDefault",
                            "defaultValue": "MATRIX-FALLBACK",
                        },
                    ],
                }
            ],
            body_contains=[field_is("out", "MATRIX-FALLBACK")],
            axis="onMissing",
        ),
        Case(
            name="onmissing-usedefault-number",
            description="onMissing=useDefault keeps a numeric defaultValue numeric.",
            filters=[
                {
                    "type": "mapping",
                    "mappings": [
                        {"source": "id", "target": "id"},
                        {
                            "source": "no_such_field",
                            "target": "out",
                            "onMissing": "useDefault",
                            "defaultValue": 1234,
                        },
                    ],
                }
            ],
            body_contains=[field_is("out", 1234)],
            axis="onMissing",
        ),
        Case(
            name="onmissing-fail",
            description="onMissing=fail aborts the pipeline when the source is absent.",
            filters=[
                {
                    "type": "mapping",
                    "mappings": [
                        {"source": "no_such_field", "target": "out", "onMissing": "fail"},
                    ],
                }
            ],
            expect_status="error",
            axis="onMissing",
        ),
        Case(
            name="onmissing-nested-path-absent",
            description="A missing nested path is treated as absent, not as an error.",
            filters=[
                {
                    "type": "mapping",
                    "mappings": [
                        {"source": "id", "target": "id"},
                        {
                            "source": "nested.deep.absent",
                            "target": "out",
                            "onMissing": "useDefault",
                            "defaultValue": "NESTED-FALLBACK",
                        },
                    ],
                }
            ],
            body_contains=[field_is("out", "NESTED-FALLBACK")],
            axis="onMissing",
        ),
        Case(
            name="onmissing-nested-path-present",
            description="A deep nested source path is resolved by the mapping filter.",
            filters=[
                {
                    "type": "mapping",
                    "mappings": [
                        {"source": "nested.deep.leaf", "target": "out"},
                    ],
                }
            ],
            body_contains=[field_is("out", "found-me")],
            axis="onMissing",
        ),
        Case(
            name="onmissing-target-only-deletes",
            description="A mapping with a target but no source deletes that field.",
            filters=[
                {
                    "type": "mapping",
                    "mappings": [
                        {"source": "id", "target": "id"},
                        {"source": "mixed", "target": "mixed"},
                        {"target": "mixed"},
                    ],
                }
            ],
            body_contains=[field_is("id", "MTX-1")],
            body_absent=["MiXeD"],
            axis="onMissing",
        ),
    ]
    return cases


# --------------------------------------------------------------------------
# Axis: set / remove across path shapes and value types
# --------------------------------------------------------------------------


def set_remove_cases() -> list[Case]:
    set_values: list[tuple[str, str, object]] = [
        ("string", "flag", "matrix-set"),
        ("int", "count", 99),
        ("float", "ratio", 2.5),
        ("bool-true", "enabled", True),
        ("bool-false", "disabled", False),
        ("null", "cleared", None),
    ]
    cases: list[Case] = []
    for label, target, value in set_values:
        cases.append(
            Case(
                name=f"set-{label}",
                description=f"set writes a {label} value and preserves its JSON type.",
                filters=[{"type": "set", "target": target, "value": value}],
                body_contains=[field_is(target, value)],
                axis="set",
            )
        )
    cases += [
        Case(
            name="set-nested-path",
            description="set creates intermediate objects for a nested target path.",
            filters=[{"type": "set", "target": "routing.bucket", "value": "matrix-bucket"}],
            body_contains=[field_is("bucket", "matrix-bucket"), '"routing":'],
            axis="set",
        ),
        Case(
            name="set-deep-nested-path",
            description="set creates a three-level target path.",
            filters=[{"type": "set", "target": "a.b.c", "value": "deep-set"}],
            body_contains=[field_is("c", "deep-set")],
            axis="set",
        ),
        Case(
            name="set-overwrites-existing",
            description="set replaces the value of an existing field.",
            filters=[{"type": "set", "target": "mixed", "value": "overwritten"}],
            body_contains=[field_is("mixed", "overwritten")],
            body_absent=["MiXeD Case"],
            axis="set",
        ),
        Case(
            name="set-overwrites-nested-existing",
            description="set replaces an existing nested value.",
            filters=[{"type": "set", "target": "nested.deep.leaf", "value": "replaced-leaf"}],
            body_contains=[field_is("leaf", "replaced-leaf")],
            body_absent=["found-me"],
            axis="set",
        ),
        Case(
            name="remove-flat-field",
            description="remove deletes a top-level field.",
            filters=[{"type": "remove", "target": "mixed"}],
            body_contains=[field_is("id", "MTX-1")],
            body_absent=["MiXeD Case"],
            axis="remove",
        ),
        Case(
            name="remove-nested-field",
            description="remove deletes a nested field but keeps its parent.",
            filters=[{"type": "remove", "target": "nested.deep.leaf"}],
            body_contains=['"nested":'],
            body_absent=["found-me"],
            axis="remove",
        ),
        Case(
            name="remove-list-of-targets",
            description="remove accepts a list and deletes every listed path.",
            filters=[{"type": "remove", "target": ["mixed", "padded", "nested.deep.leaf"]}],
            body_contains=[field_is("id", "MTX-1")],
            body_absent=["MiXeD Case", "spaced value", "found-me"],
            axis="remove",
        ),
        Case(
            name="remove-absent-field-is-noop",
            description="Removing a field that does not exist leaves the record intact.",
            filters=[{"type": "remove", "target": "no_such_field"}],
            body_contains=[field_is("id", "MTX-1")],
            axis="remove",
        ),
        Case(
            name="remove-then-set-same-path",
            description="Filters apply in order: a removed path can be re-created by a later set.",
            filters=[
                {"type": "remove", "target": "mixed"},
                {"type": "set", "target": "mixed", "value": "recreated"},
            ],
            body_contains=[field_is("mixed", "recreated")],
            body_absent=["MiXeD Case"],
            axis="remove",
        ),
    ]
    return cases


# --------------------------------------------------------------------------
# Axis: condition expressions and branching
# --------------------------------------------------------------------------


def condition_cases() -> list[Case]:
    # (label, expression, whether the then-branch is expected to run)
    exprs: list[tuple[str, str, bool]] = [
        ("eq-string-true", 'mixed == "MiXeD Case"', True),
        ("eq-string-false", 'mixed == "other"', False),
        ("ne-string-true", 'mixed != "other"', True),
        ("gt-number-true", "int_val > 3", True),
        ("gt-number-false", "int_val > 70", False),
        ("lt-number-true", "int_val < 70", True),
        ("gte-number-boundary", "int_val >= 7", True),
        ("lte-number-boundary", "int_val <= 7", True),
        ("and-both-true", 'int_val > 3 && mixed == "MiXeD Case"', True),
        ("and-one-false", 'int_val > 3 && mixed == "nope"', False),
        ("or-one-true", 'int_val > 70 || mixed == "MiXeD Case"', True),
        ("or-both-false", 'int_val > 70 || mixed == "nope"', False),
        ("not-operator", "!(int_val > 70)", True),
        ("bool-field-direct", "bool_val", True),
        ("nested-field-access", 'nested.deep.leaf == "found-me"', True),
        ("arithmetic", "int_val * 2 == 14", True),
        ("string-contains", 'mixed contains "Case"', True),
        ("in-operator", 'int_val in [5, 7, 9]', True),
    ]
    cases: list[Case] = []
    for label, expr, then_runs in exprs:
        marker_then, marker_else = "BRANCH-THEN", "BRANCH-ELSE"
        cases.append(
            Case(
                name=f"condition-{label}",
                description=(
                    f"condition `{expr}` routes to the "
                    f"{'then' if then_runs else 'else'} branch."
                ),
                filters=[
                    {
                        "type": "condition",
                        "expression": expr,
                        "then": [{"type": "set", "target": "branch", "value": marker_then}],
                        "else": [{"type": "set", "target": "branch", "value": marker_else}],
                    }
                ],
                body_contains=[field_is("branch", marker_then if then_runs else marker_else)],
                body_absent=[marker_else if then_runs else marker_then],
                axis="condition",
            )
        )
    cases += [
        Case(
            name="condition-then-only-no-else",
            description="With no else branch a non-matching record passes through unchanged.",
            filters=[
                {
                    "type": "condition",
                    "expression": 'mixed == "nope"',
                    "then": [{"type": "set", "target": "branch", "value": "SHOULD-NOT-RUN"}],
                }
            ],
            body_contains=[field_is("id", "MTX-1")],
            body_absent=["SHOULD-NOT-RUN"],
            axis="condition",
        ),
        Case(
            name="condition-nested-conditions",
            description="A condition nested inside another condition's then branch is evaluated.",
            filters=[
                {
                    "type": "condition",
                    "expression": "int_val > 3",
                    "then": [
                        {
                            "type": "condition",
                            "expression": 'mixed == "MiXeD Case"',
                            "then": [{"type": "set", "target": "branch", "value": "NESTED-HIT"}],
                        }
                    ],
                }
            ],
            body_contains=[field_is("branch", "NESTED-HIT")],
            axis="condition",
        ),
        Case(
            name="condition-drop-in-then",
            description="A drop inside the then branch removes the matching record entirely.",
            filters=[
                {
                    "type": "condition",
                    "expression": "int_val > 3",
                    "then": [{"type": "drop"}],
                }
            ],
            body_absent=["MTX-1"],
            axis="condition",
        ),
        Case(
            name="condition-multiple-filters-in-branch",
            description="A branch runs every filter it contains, in order.",
            filters=[
                {
                    "type": "condition",
                    "expression": "bool_val",
                    "then": [
                        {"type": "set", "target": "first", "value": "one"},
                        {"type": "set", "target": "second", "value": "two"},
                        {"type": "remove", "target": "mixed"},
                    ],
                }
            ],
            body_contains=[field_is("first", "one"), field_is("second", "two")],
            body_absent=["MiXeD Case"],
            axis="condition",
        ),
    ]
    return cases


# --------------------------------------------------------------------------
# Axis: script filter (inline JavaScript via Goja)
# --------------------------------------------------------------------------


def script_cases() -> list[Case]:
    # (label, body of transform(record), expected target/value)
    scripts: list[tuple[str, str, str, object]] = [
        ("read-field", 'record.out = record.mixed; return record;', "out", "MiXeD Case"),
        ("string-method", 'record.out = record.mixed.toUpperCase(); return record;', "out", "MIXED CASE"),
        ("arithmetic", 'record.out = record.int_val * 6; return record;', "out", 42),
        ("float-arithmetic", 'record.out = record.float_val + 0.5; return record;', "out", 2),
        ("concat", 'record.out = record.id + "-suffix"; return record;', "out", "MTX-1-suffix"),
        ("nested-read", 'record.out = record.nested.deep.leaf; return record;', "out", "found-me"),
        ("array-length", 'record.out = record.pipe_list.length; return record;', "out", 3),
        ("array-join", 'record.out = record.pipe_list.join("+"); return record;', "out", "one+two+three"),
        ("boolean-logic", 'record.out = record.bool_val && record.int_val > 3; return record;', "out", True),
        ("ternary", 'record.out = record.int_val > 3 ? "big" : "small"; return record;', "out", "big"),
        ("json-parse-number", 'record.out = parseInt(record.int_str, 10) + 1; return record;', "out", 43),
        ("delete-field", 'delete record.mixed; record.out = "deleted"; return record;', "out", "deleted"),
        ("new-nested-object", 'record.out = {inner: "built"}; return record;', "inner", "built"),
        ("null-handling", 'record.out = record.null_val === null ? "was-null" : "not-null"; return record;', "out", "was-null"),
        ("empty-string-check", 'record.out = record.empty_str === "" ? "empty" : "filled"; return record;', "out", "empty"),
    ]
    cases: list[Case] = []
    for label, body, target, expected in scripts:
        cases.append(
            Case(
                name=f"script-{label}",
                description=f"inline script: {label}.",
                filters=[{"type": "script", "script": f"function transform(record) {{ {body} }}"}],
                body_contains=[field_is(target, expected)],
                axis="script",
            )
        )
    cases.append(
        Case(
            name="script-delete-removes-field",
            description="A script deleting a field drops it from the forwarded record.",
            filters=[{"type": "script", "script": "function transform(record) { delete record.mixed; return record; }"}],
            body_contains=[field_is("id", "MTX-1")],
            body_absent=["MiXeD Case"],
            axis="script",
        )
    )
    cases.append(
        Case(
            name="script-throws-fails-pipeline",
            description="A script that throws fails the pipeline under the default onError=fail.",
            filters=[
                {
                    "type": "script",
                    "script": 'function transform(record) { throw new Error("matrix-script-boom"); }',
                }
            ],
            expect_status="error",
            axis="script",
        )
    )
    return cases


# --------------------------------------------------------------------------
# Axis: loop filter
# --------------------------------------------------------------------------


def loop_cases() -> list[Case]:
    """Loop cells.

    Inside a loop the filters see a scope, not the record: buildLoopScope builds
    {record: <root>, _metadata: <meta>, <itemName>: <item>}. Writing to the
    record therefore needs the explicit `record.` prefix, while the item and the
    loop metadata are read by their bare alias.
    """
    cases = [
        Case(
            name="loop-sets-from-item",
            description="loop iterates an array and writes to the parent record via the record. prefix.",
            filters=[
                {
                    "type": "loop",
                    "field": "pipe_list",
                    "itemName": "entry",
                    "filters": [
                        {
                            "type": "condition",
                            "expression": 'entry == "two"',
                            "then": [{"type": "set", "target": "record.found", "value": "saw-two"}],
                        }
                    ],
                }
            ],
            body_contains=[field_is("found", "saw-two")],
            axis="loop",
        ),
        Case(
            name="loop-index-metadata",
            description="loop exposes the current index as _metadata.loop.<itemName>.index.",
            filters=[
                {
                    "type": "loop",
                    "field": "pipe_list",
                    "itemName": "entry",
                    "filters": [
                        {
                            "type": "condition",
                            "expression": "_metadata.loop.entry.index == 2",
                            "then": [{"type": "set", "target": "record.last_index", "value": "reached-2"}],
                        }
                    ],
                }
            ],
            body_contains=[field_is("last_index", "reached-2")],
            axis="loop",
        ),
        Case(
            name="loop-index-metadata-first-item",
            description="The loop index starts at 0 for the first item.",
            filters=[
                {
                    "type": "loop",
                    "field": "pipe_list",
                    "itemName": "entry",
                    "filters": [
                        {
                            "type": "condition",
                            "expression": "_metadata.loop.entry.index == 0",
                            "then": [{"type": "set", "target": "record.first_index", "value": "zero-based"}],
                        }
                    ],
                }
            ],
            body_contains=[field_is("first_index", "zero-based")],
            axis="loop",
        ),
        Case(
            name="loop-over-empty-array",
            description="loop over an empty array runs no inner filter and keeps the record.",
            filters=[
                {"type": "set", "target": "empty_list", "value": []},
                {
                    "type": "loop",
                    "field": "empty_list",
                    "itemName": "entry",
                    "filters": [{"type": "set", "target": "record.should_not_set", "value": "NEVER"}],
                },
            ],
            body_contains=[field_is("id", "MTX-1")],
            body_absent=["NEVER"],
            axis="loop",
        ),
        Case(
            name="loop-multiple-inner-filters",
            description="Every filter inside a loop body runs for each item.",
            filters=[
                {
                    "type": "loop",
                    "field": "pipe_list",
                    "itemName": "entry",
                    "filters": [
                        {"type": "set", "target": "record.touched", "value": "yes"},
                        {
                            "type": "condition",
                            "expression": 'entry == "three"',
                            "then": [{"type": "set", "target": "record.third", "value": "hit"}],
                        },
                    ],
                }
            ],
            body_contains=[field_is("touched", "yes"), field_is("third", "hit")],
            axis="loop",
        ),
        Case(
            name="loop-then-remove-source-array",
            description="A loop flattens values onto the record before the source array is removed.",
            filters=[
                {
                    "type": "loop",
                    "field": "pipe_list",
                    "itemName": "entry",
                    "filters": [
                        {
                            "type": "condition",
                            "expression": 'entry == "one"',
                            "then": [{"type": "set", "target": "record.first_entry", "value": "one"}],
                        }
                    ],
                },
                {"type": "remove", "target": "pipe_list"},
            ],
            body_contains=[field_is("first_entry", "one")],
            body_absent=['"pipe_list"'],
            axis="loop",
        ),
        Case(
            name="loop-missing-field-is-noop",
            description=(
                "loop over an absent field is a deliberate no-op (processRecord returns early), "
                "not an error: the record passes through untouched."
            ),
            filters=[
                {
                    "type": "loop",
                    "field": "no_such_array",
                    "itemName": "entry",
                    "filters": [{"type": "set", "target": "record.should_not_set", "value": "NEVER"}],
                }
            ],
            body_contains=[field_is("id", "MTX-1")],
            body_absent=["NEVER"],
            axis="loop",
        ),
        Case(
            name="loop-non-array-field-fails",
            description="loop over a field that is not an array fails with ErrLoopFieldNotArray.",
            filters=[
                {
                    "type": "loop",
                    "field": "mixed",
                    "itemName": "entry",
                    "filters": [{"type": "set", "target": "record.x", "value": "y"}],
                }
            ],
            expect_status="error",
            log_contains=["not an array"],
            skip_sink_assertions=True,
            axis="loop",
        ),
        Case(
            name="loop-reads-item-into-record",
            description="An inner mapping copies the item value itself onto the record.",
            filters=[
                {
                    "type": "loop",
                    "field": "pipe_list",
                    "itemName": "entry",
                    "filters": [
                        {
                            "type": "condition",
                            "expression": 'entry == "two"',
                            "then": [
                                {
                                    "type": "mapping",
                                    "mappings": [{"source": "entry", "target": "record.copied"}],
                                }
                            ],
                        }
                    ],
                }
            ],
            body_contains=[field_is("copied", "two")],
            axis="loop",
        ),
    ]
    return cases


# --------------------------------------------------------------------------
# Axis: drop
# --------------------------------------------------------------------------


def drop_cases() -> list[Case]:
    return [
        Case(
            name="drop-unconditional",
            description="An unconditional drop removes every record, so nothing is sent.",
            filters=[{"type": "drop"}],
            skip_sink_assertions=True,
            extra_assertions=[{"http_count_eq_zero": {"method": "POST", "path": SINK_PATH}}],
            axis="drop",
        ),
        Case(
            name="drop-in-else-branch",
            description="A drop in the else branch removes records that fail the condition.",
            filters=[
                {
                    "type": "condition",
                    "expression": 'mixed == "no-match"',
                    "then": [{"type": "set", "target": "kept", "value": "yes"}],
                    "else": [{"type": "drop"}],
                }
            ],
            skip_sink_assertions=True,
            extra_assertions=[{"http_count_eq_zero": {"method": "POST", "path": SINK_PATH}}],
            axis="drop",
        ),
        Case(
            name="drop-after-set-still-drops",
            description="Filters that ran before a drop do not resurrect the record.",
            filters=[
                {"type": "set", "target": "marker", "value": "MATRIX-DROPPED"},
                {"type": "drop"},
            ],
            skip_sink_assertions=True,
            extra_assertions=[
                {"http_count_eq_zero": {"method": "POST", "path": SINK_PATH, "body_contains": "MATRIX-DROPPED"}}
            ],
            axis="drop",
        ),
    ]


# --------------------------------------------------------------------------
# Axis: template rendering in the output request
# --------------------------------------------------------------------------


def template_cases() -> list[Case]:
    # (label, body template, expected substring in the outgoing body)
    bodies: list[tuple[str, str, str]] = [
        ("flat-field", '{"v": "{{ record.mixed }}"}', '"v": "MiXeD Case"'),
        ("nested-field", '{"v": "{{ record.nested.deep.leaf }}"}', '"v": "found-me"'),
        ("number-field", '{"v": {{ record.int_val }}}', '"v": 7'),
        ("bool-field", '{"v": {{ record.bool_val }}}', '"v": true'),
        ("two-fields", '{"a": "{{ record.id }}", "b": "{{ record.mixed }}"}', '"a": "MTX-1"'),
        ("upper-filter", '{"v": "{{ record.mixed | upper }}"}', '"v": "MIXED CASE"'),
        ("lower-filter", '{"v": "{{ record.mixed | lower }}"}', '"v": "mixed case"'),
        ("default-filter-on-missing", '{"v": "{{ record.nope | default(\'fallback\') }}"}', '"v": "fallback"'),
        ("literal-text-around", '{"v": "prefix-{{ record.id }}-suffix"}', '"v": "prefix-MTX-1-suffix"'),
    ]
    cases: list[Case] = []
    for label, body, expected in bodies:
        cases.append(
            Case(
                name=f"template-{label}",
                description=f"output body template: {label}.",
                filters=[],
                skip_sink_assertions=True,
                output_override={"requestMode": "single", "body": body},
                extra_assertions=[
                    {
                        "http_count_ge": {
                            "method": "POST",
                            "path": SINK_PATH,
                            "body_contains": expected,
                            "expected": 1,
                        }
                    }
                ],
                axis="template",
            )
        )
    return cases


# --------------------------------------------------------------------------
# Axis: successCondition matrix
# --------------------------------------------------------------------------


def success_cases() -> list[Case]:
    # (label, destination status, success block, expected pipeline status)
    combos: list[tuple[str, int, dict, str]] = [
        ("statuscodes-single-match", 201, {"statusCodes": [201]}, "success"),
        ("statuscodes-single-mismatch", 201, {"statusCodes": [200]}, "error"),
        ("statuscodes-list-match", 202, {"statusCodes": [200, 201, 202]}, "success"),
        ("statuscodes-list-mismatch", 418, {"statusCodes": [200, 201, 202]}, "error"),
        ("statuscodes-accepts-204", 204, {"statusCodes": [204]}, "success"),
        ("statuscodes-accepts-redirect", 302, {"statusCodes": [302]}, "success"),
        ("statuscodes-accepts-500", 500, {"statusCodes": [500]}, "success"),
        ("default-accepts-201", 201, {}, "success"),
        ("default-accepts-204", 204, {}, "success"),
        ("default-rejects-418", 418, {}, "error"),
        ("default-rejects-302", 302, {}, "error"),
        ("expression-on-statuscode-true", 418, {"expression": "statusCode == 418"}, "success"),
        ("expression-on-statuscode-false", 201, {"expression": "statusCode == 418"}, "error"),
        ("expression-on-body-true", 201, {"expression": 'body.state == "done"'}, "success"),
        ("expression-on-body-false", 201, {"expression": 'body.state == "pending"'}, "error"),
        ("expression-numeric-body", 202, {"expression": "body.code == 202"}, "success"),
        ("both-agree", 201, {"statusCodes": [201], "expression": 'body.state == "done"'}, "success"),
        ("both-status-ok-expression-false", 201, {"statusCodes": [201], "expression": 'body.state == "nope"'}, "error"),
        ("both-status-bad-expression-true", 418, {"statusCodes": [201], "expression": "statusCode == 418"}, "error"),
    ]
    cases: list[Case] = []
    for label, status, success, expected in combos:
        output: dict = {
            "endpoint": f"http://localhost:18080/destination/matrix/status/{status}",
            "retry": {"maxAttempts": 0},
        }
        if success:
            output["success"] = success
        cases.append(
            Case(
                name=f"success-{label}",
                description=(
                    f"destination returns {status}; success={success or 'default'} "
                    f"means the pipeline must end as {expected}."
                ),
                filters=[],
                skip_sink_assertions=True,
                expect_status=expected,
                output_override=output,
                extra_assertions=[
                    {
                        "http_count_ge": {
                            "method": "POST",
                            "path": f"/destination/matrix/status/{status}",
                            "expected": 1,
                        }
                    }
                ],
                axis="success",
            )
        )
    return cases


# --------------------------------------------------------------------------
# Axis: output HTTP method x requestMode
# --------------------------------------------------------------------------


def method_cases() -> list[Case]:
    cases: list[Case] = []
    for method in ("POST", "PUT", "PATCH", "DELETE", "GET"):
        for mode in ("batch", "single"):
            cases.append(
                Case(
                    name=f"method-{method.lower()}-{mode}",
                    description=f"httpRequest output issues {method} in {mode} mode.",
                    filters=[],
                    skip_sink_assertions=True,
                    output_override={
                        "endpoint": "http://localhost:18080/destination/matrix/anymethod",
                        "method": method,
                        "requestMode": mode,
                    },
                    extra_assertions=[
                        {
                            "http_count_ge": {
                                "method": method,
                                "path": "/destination/matrix/anymethod",
                                "status": 200,
                                "expected": 1,
                            }
                        }
                    ],
                    axis="method",
                )
            )
    return cases


# --------------------------------------------------------------------------
# Axis: pagination boundary values
# --------------------------------------------------------------------------


def pagination_edge_cases() -> list[Case]:
    return [
        Case(
            name="pagination-single-page-stops",
            description="totalPages 1 stops the loop after the first page.",
            filters=[],
            skip_sink_assertions=True,
            input_override={
                "endpoint": "http://localhost:18080/source/matrix/single-page",
                "pagination": {"type": "page", "param": "page", "totalPagesField": "total_pages"},
            },
            extra_assertions=[
                {"http_count_eq": {"method": "GET", "path": "/source/matrix/single-page", "expected": 1}},
                {
                    "http_count_ge": {
                        "method": "POST",
                        "path": SINK_PATH,
                        "body_contains": "SINGLE-1",
                        "expected": 1,
                    }
                },
            ],
            axis="pagination",
        ),
        Case(
            name="pagination-empty-first-page-stops",
            description="An empty first page ends pagination without sending anything.",
            filters=[],
            skip_sink_assertions=True,
            input_override={
                "endpoint": "http://localhost:18080/source/matrix/empty-page",
                "pagination": {"type": "page", "param": "page", "totalPagesField": "total_pages"},
            },
            extra_assertions=[
                {"http_count_eq": {"method": "GET", "path": "/source/matrix/empty-page", "expected": 1}},
                {"http_count_eq_zero": {"method": "POST", "path": SINK_PATH}},
            ],
            axis="pagination",
        ),
        Case(
            name="pagination-missing-meta-stops-after-short-page",
            description=(
                "Without the totalPages field the loop still terminates: a page shorter "
                "than the limit ends it."
            ),
            filters=[],
            skip_sink_assertions=True,
            input_override={
                "endpoint": "http://localhost:18080/source/matrix/no-meta",
                "pagination": {
                    "type": "offset",
                    "param": "offset",
                    "limitParam": "limit",
                    "limit": 10,
                    "totalField": "total",
                },
            },
            extra_assertions=[
                {"http_count_eq": {"method": "GET", "path": "/source/matrix/no-meta", "expected": 1}},
                {
                    "http_count_ge": {
                        "method": "POST",
                        "path": SINK_PATH,
                        "body_contains": "NOMETA-1",
                        "expected": 1,
                    }
                },
            ],
            axis="pagination",
        ),
        Case(
            name="pagination-limit-one-emits-page-size",
            description="limit 1 with a limitParam emits that page size on the request.",
            filters=[],
            skip_sink_assertions=True,
            input_override={
                "endpoint": "http://localhost:18080/source/matrix/single-page",
                "pagination": {
                    "type": "page",
                    "param": "page",
                    "limitParam": "per_page",
                    "limit": 1,
                    "totalPagesField": "total_pages",
                },
            },
            extra_assertions=[
                {
                    "http_count_ge": {
                        "method": "GET",
                        "path": "/source/matrix/single-page",
                        "query": {"per_page": "1", "page": "1"},
                        "expected": 1,
                    }
                }
            ],
            axis="pagination",
        ),
    ]


# --------------------------------------------------------------------------
# Axis: onError across filter modules
# --------------------------------------------------------------------------


def on_error_cases() -> list[Case]:
    # A mapping transform that always fails, run under each onError strategy.
    broken_mapping = {
        "type": "mapping",
        "mappings": [{"source": "bad_int_str", "target": "out", "transforms": [{"op": "toInt"}]}],
    }
    broken_script = {
        "type": "script",
        "script": 'function transform(record) { throw new Error("matrix-onerror"); }',
    }
    cases: list[Case] = []
    for module_label, base in (("mapping", broken_mapping), ("script", broken_script)):
        for strategy, expected in (("fail", "error"), ("skip", "success"), ("log", "success")):
            filters = [dict(base)]
            filters[0]["onError"] = strategy
            cases.append(
                Case(
                    name=f"onerror-{module_label}-{strategy}",
                    description=(
                        f"a failing {module_label} filter with onError={strategy} ends the run "
                        f"as {expected}."
                    ),
                    filters=filters,
                    skip_sink_assertions=True,
                    expect_status=expected,
                    axis="onError",
                )
            )
    return cases


# --------------------------------------------------------------------------
# Axis: transform chains — composition order matters
# --------------------------------------------------------------------------


def transform_chain_cases() -> list[Case]:
    chains: list[tuple[str, str, list[dict], object]] = [
        ("trim-then-uppercase", "padded", [{"op": "trim"}, {"op": "uppercase"}], "SPACED VALUE"),
        ("uppercase-then-trim", "padded", [{"op": "uppercase"}, {"op": "trim"}], "SPACED VALUE"),
        ("trim-then-lowercase", "padded", [{"op": "trim"}, {"op": "lowercase"}], "spaced value"),
        (
            "split-then-join-roundtrip",
            "csv",
            [{"op": "split"}, {"op": "join", "separator": "|"}],
            "alpha|beta|gamma",
        ),
        (
            "join-then-uppercase",
            "pipe_list",
            [{"op": "join", "separator": "-"}, {"op": "uppercase"}],
            "ONE-TWO-THREE",
        ),
        ("toint-then-tostring", "int_str", [{"op": "toInt"}, {"op": "toString"}], "42"),
        ("tostring-then-toint", "int_val", [{"op": "toString"}, {"op": "toInt"}], 7),
        ("tofloat-then-tostring", "float_str", [{"op": "toFloat"}, {"op": "toString"}], "98.5"),
        ("tobool-then-tostring", "bool_str", [{"op": "toBool"}, {"op": "toString"}], "true"),
        (
            "trim-replace-uppercase",
            "padded",
            [
                {"op": "trim"},
                {"op": "replace", "pattern": " ", "replacement": "_"},
                {"op": "uppercase"},
            ],
            "SPACED_VALUE",
        ),
        (
            "dateformat-then-uppercase-noop",
            "date_iso",
            [{"op": "dateFormat", "format": "YYYY-MM-DD"}, {"op": "uppercase"}],
            "2026-03-04",
        ),
        (
            "toarray-then-join",
            "mixed",
            [{"op": "toArray"}, {"op": "join", "separator": ";"}],
            "MiXeD Case",
        ),
        ("trim-then-toarray", "padded", [{"op": "trim"}, {"op": "toArray"}], ["spaced value"]),
        (
            "split-then-toarray-passthrough",
            "csv",
            [{"op": "split"}, {"op": "toArray"}],
            ["alpha", "beta", "gamma"],
        ),
    ]
    cases: list[Case] = []
    for label, src, transforms, expected in chains:
        ops = " -> ".join(t["op"] for t in transforms)
        cases.append(
            Case(
                name=f"chain-{label}",
                description=f"transform chain {ops} on {src}.",
                filters=[
                    {
                        "type": "mapping",
                        "mappings": [{"source": src, "target": "out", "transforms": transforms}],
                    }
                ],
                body_contains=[field_is("out", expected)],
                axis="chain",
            )
        )
    # A chain whose second op cannot handle the first op's output.
    cases.append(
        Case(
            name="chain-split-then-toint-fails",
            description="A chain fails when a later op cannot convert the previous output.",
            filters=[
                {
                    "type": "mapping",
                    "mappings": [
                        {"source": "csv", "target": "out", "transforms": [{"op": "split"}, {"op": "toInt"}]}
                    ],
                }
            ],
            expect_status="error",
            log_contains=["cannot convert"],
            skip_sink_assertions=True,
            axis="chain",
        )
    )
    return cases


# --------------------------------------------------------------------------
# Axis: templates in output headers
# --------------------------------------------------------------------------


def template_header_cases() -> list[Case]:
    headers: list[tuple[str, str, str]] = [
        ("flat", "{{ record.id }}", "MTX-1"),
        ("nested", "{{ record.nested.deep.leaf }}", "found-me"),
        ("number", "{{ record.int_val }}", "7"),
        ("upper-filter", "{{ record.mixed | upper }}", "MIXED CASE"),
        ("default-on-missing", "{{ record.nope | default('none') }}", "none"),
        ("literal-around", "v-{{ record.id }}-end", "v-MTX-1-end"),
    ]
    cases: list[Case] = []
    for label, template, expected in headers:
        cases.append(
            Case(
                name=f"template-header-{label}",
                description=f"output header template: {label}.",
                filters=[],
                skip_sink_assertions=True,
                output_override={
                    "requestMode": "single",
                    "headers": {"Content-Type": "application/json", "X-Matrix": template},
                },
                extra_assertions=[
                    {
                        "http_count_ge": {
                            "method": "POST",
                            "path": SINK_PATH,
                            "headers": {"X-Matrix": expected},
                            "expected": 1,
                        }
                    }
                ],
                axis="template",
            )
        )
    return cases


# --------------------------------------------------------------------------
# Axis: extra condition operators
# --------------------------------------------------------------------------


def condition_extra_cases() -> list[Case]:
    exprs: list[tuple[str, str, bool]] = [
        ("startswith", 'mixed startsWith "MiXeD"', True),
        ("endswith", 'mixed endsWith "Case"', True),
        ("matches-regex", 'mixed matches "^MiXeD"', True),
        ("not-contains", '!(mixed contains "zzz")', True),
        ("len-of-array", "len(pipe_list) == 3", True),
        ("len-of-string", "len(id) == 5", True),
        ("nil-check-on-null", "null_val == nil", True),
        ("nil-check-on-missing", "no_such_field == nil", True),
        ("empty-string-equality", 'empty_str == ""', True),
        ("nested-numeric-compare", "int_val + float_val > 8", True),
        # JSON numbers arrive as float64, and expr-lang's % needs integers, so a
        # cast is required. Both halves are locked below.
        ("modulo-needs-int-cast", "int(int_val) % 2 == 1", True),
        ("chained-comparison", "int_val > 1 && int_val < 100 && bool_val", True),
    ]
    cases: list[Case] = []
    cases.append(
        Case(
            name="condition-op-modulo-on-float-fails",
            description=(
                "Modulo directly on a JSON number fails: every JSON number is a float64 and "
                "expr-lang's % requires integers. Use int(field) % n instead."
            ),
            filters=[
                {
                    "type": "condition",
                    "expression": "int_val % 2 == 1",
                    "then": [{"type": "set", "target": "branch", "value": "OP-THEN"}],
                }
            ],
            expect_status="error",
            log_contains=["invalid operation: float64 % int"],
            skip_sink_assertions=True,
            axis="condition",
        )
    )
    for label, expr, then_runs in exprs:
        cases.append(
            Case(
                name=f"condition-op-{label}",
                description=f"condition operator `{expr}`.",
                filters=[
                    {
                        "type": "condition",
                        "expression": expr,
                        "then": [{"type": "set", "target": "branch", "value": "OP-THEN"}],
                        "else": [{"type": "set", "target": "branch", "value": "OP-ELSE"}],
                    }
                ],
                body_contains=[field_is("branch", "OP-THEN" if then_runs else "OP-ELSE")],
                axis="condition",
            )
        )
    return cases


# --------------------------------------------------------------------------
# Axis: retry configuration matrix against always-failing destinations
# --------------------------------------------------------------------------


def retry_matrix_cases() -> list[Case]:
    fast = {"delayMs": 20, "backoffMultiplier": 1, "maxDelayMs": 50}
    combos: list[tuple[str, str, dict, int]] = [
        # (label, destination path, retry config, expected request count)
        (
            "500-no-retry",
            "/reliability/destination/always-500",
            {"maxAttempts": 0, "retryableStatusCodes": [500], **fast},
            1,
        ),
        (
            "500-one-retry",
            "/reliability/destination/always-500",
            {"maxAttempts": 1, "retryableStatusCodes": [500], **fast},
            2,
        ),
        (
            "500-three-retries",
            "/reliability/destination/always-500",
            {"maxAttempts": 3, "retryableStatusCodes": [500], **fast},
            4,
        ),
        (
            "500-not-in-retryable-list",
            "/reliability/destination/always-500",
            {"maxAttempts": 3, "retryableStatusCodes": [503], **fast},
            1,
        ),
        (
            "429-retryable",
            "/reliability/destination/always-429",
            {"maxAttempts": 2, "retryableStatusCodes": [429], **fast},
            3,
        ),
        (
            "429-not-retryable",
            "/reliability/destination/always-429",
            {"maxAttempts": 2, "retryableStatusCodes": [500], **fast},
            1,
        ),
        (
            "503-body-hint-true",
            "/reliability/destination/always-503-retryable",
            {
                "maxAttempts": 2,
                "retryableStatusCodes": [503],
                "retryHintFromBody": "body.retryable == true",
                **fast,
            },
            3,
        ),
        (
            "503-body-hint-false-overrides",
            "/reliability/destination/always-503-nonretryable",
            {
                "maxAttempts": 2,
                "retryableStatusCodes": [503],
                "retryHintFromBody": "body.retryable == true",
                **fast,
            },
            1,
        ),
        (
            "backoff-multiplier-two",
            "/reliability/destination/always-500",
            {"maxAttempts": 2, "retryableStatusCodes": [500], "delayMs": 20, "backoffMultiplier": 2, "maxDelayMs": 100},
            3,
        ),
        (
            "max-delay-caps-backoff",
            "/reliability/destination/always-500",
            {"maxAttempts": 2, "retryableStatusCodes": [500], "delayMs": 40, "backoffMultiplier": 10, "maxDelayMs": 45},
            3,
        ),
    ]
    cases: list[Case] = []
    for label, path, retry, expected_calls in combos:
        cases.append(
            Case(
                name=f"retry-{label}",
                description=(
                    f"retry {retry} against {path} must issue exactly {expected_calls} request(s)."
                ),
                filters=[],
                skip_sink_assertions=True,
                expect_status="error",
                output_override={
                    "endpoint": f"http://localhost:18080{path}",
                    "retry": retry,
                },
                extra_assertions=[
                    {"http_count_eq": {"method": "POST", "path": path, "expected": expected_calls}}
                ],
                axis="retry",
            )
        )
    return cases


# --------------------------------------------------------------------------
# Axis: dataField response shapes
# --------------------------------------------------------------------------


def datafield_cases() -> list[Case]:
    shapes: list[tuple[str, str, str | None, str]] = [
        # (label, source path, dataField (None = omit), expected record id)
        ("explicit-data", "/source/matrix/record", "data", "MTX-1"),
        ("implicit-data", "/source/matrix/record", None, "MTX-1"),
        ("implicit-items", "/source/matrix/items", None, "SHAPE-items"),
        ("implicit-results", "/source/matrix/results", None, "SHAPE-results"),
        ("implicit-records", "/source/matrix/records", None, "SHAPE-records"),
        ("explicit-items", "/source/matrix/items", "items", "SHAPE-items"),
        ("root-array-no-datafield", "/source/matrix/root-array", None, "ROOT-1"),
        ("nested-datafield-path", "/source/matrix/deep", "payload.inner.rows", "DEEP-1"),
    ]
    cases: list[Case] = []
    for label, path, data_field, expected_id in shapes:
        override: dict = {"endpoint": f"http://localhost:18080{path}"}
        if data_field is None:
            override["dataField"] = None
        else:
            override["dataField"] = data_field
        cases.append(
            Case(
                name=f"datafield-{label}",
                description=f"input response shape: {label}.",
                filters=[],
                body_contains=[field_is("id", expected_id)],
                input_override=override,
                axis="datafield",
            )
        )
    return cases


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------


def render_pipeline(case: Case) -> str:
    input_block = {
        "type": "httpPolling",
        "schedule": "* * * * * *",
        "endpoint": SOURCE,
        "dataField": "data",
    }
    input_block.update(case.input_override)
    # An override of None means "omit this key" (used to test dataField fallback).
    input_block = {k: v for k, v in input_block.items() if v is not None}
    output_block = {
        "type": "httpRequest",
        "endpoint": SINK,
        "method": "POST",
        "headers": {"Content-Type": "application/json"},
    }
    output_block.update(case.output_override)
    doc = {
        "name": PREFIX + case.name,
        "version": "1.0.0",
        "description": case.description,
        "tags": ["test-lab", "generated", case.axis],
        "input": input_block,
        "filters": case.filters,
        "output": output_block,
    }
    return HEADER + json.dumps(doc, indent=2) + "\n"


def render_scenario(case: Case) -> str:
    assertions: list[dict] = []
    if case.skip_sink_assertions and (case.body_contains or case.body_absent):
        raise SystemExit(f"{case.name}: skip_sink_assertions set but body assertions given")
    for needle in case.body_contains:
        assertions.append(
            {
                "http_count_ge": {
                    "method": "POST",
                    "path": SINK_PATH,
                    "body_contains": needle,
                    "expected": 1,
                }
            }
        )
    for needle in case.body_absent:
        assertions.append(
            {
                "http_count_eq_zero": {
                    "method": "POST",
                    "path": SINK_PATH,
                    "body_contains": needle,
                }
            }
        )
    assertions.extend(case.extra_assertions)
    for needle in case.log_contains:
        assertions.append({"log_contains": needle})
    assertions.append({"log_not_contains": "panic:"})

    doc = {
        "name": PREFIX + case.name,
        "description": case.description,
        "pipeline": f"test-lab/pipelines/{PREFIX}{case.name}.yaml",
        "expect_status": case.expect_status,
        # These cells never touch the database, so skip that reset to keep the
        # generated layer fast. The mapping reload stays on: without it a stub
        # added since the lab booted would 404 and look like a runtime bug.
        "setup": {"reset_db": False},
        "assertions": assertions,
    }
    return HEADER + json.dumps(doc, indent=2) + "\n"


def all_cases() -> list[Case]:
    cases = (
        transform_cases()
        + on_missing_cases()
        + set_remove_cases()
        + condition_cases()
        + script_cases()
        + loop_cases()
        + drop_cases()
        + template_cases()
        + success_cases()
        + method_cases()
        + pagination_edge_cases()
        + on_error_cases()
        + transform_chain_cases()
        + template_header_cases()
        + condition_extra_cases()
        + retry_matrix_cases()
        + datafield_cases()
    )
    seen: set[str] = set()
    for case in cases:
        if case.name in seen:
            raise SystemExit(f"duplicate generated case name: {case.name}")
        seen.add(case.name)
    return cases


def clean() -> int:
    removed = 0
    for directory in (PIPELINES, SCENARIOS):
        for path in sorted(directory.glob(f"{PREFIX}*.yaml")):
            path.unlink()
            removed += 1
    return removed


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--clean", action="store_true", help="remove generated files and exit")
    parser.add_argument("--list", action="store_true", help="list generated case names and exit")
    args = parser.parse_args(argv[1:])

    if args.clean:
        print(f"removed {clean()} generated file(s)")
        return 0

    cases = all_cases()
    if args.list:
        by_axis: dict[str, int] = {}
        for case in cases:
            by_axis[case.axis] = by_axis.get(case.axis, 0) + 1
            print(f"{case.axis:12} {PREFIX}{case.name}")
        print("\ntotals:")
        for axis, count in sorted(by_axis.items()):
            print(f"  {axis:12} {count}")
        print(f"  {'TOTAL':12} {len(cases)}")
        return 0

    clean()
    for case in cases:
        (PIPELINES / f"{PREFIX}{case.name}.yaml").write_text(render_pipeline(case))
        (SCENARIOS / f"{PREFIX}{case.name}.yaml").write_text(render_scenario(case))
    print(f"generated {len(cases)} pipeline/scenario pair(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
